using MTGDeckBuilder.MTGJson.AllPrintings;
using MTGDeckBuilder.MTGJson.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MTGDeckBuilder.MTGJson.Mapping
{
    internal static class AllPrintingsMapper
    {
        public static ParsedAllPrintingsSet MapToParsedAllPrintingsSet(MTGJsonAllPrintingsSet deserializedSet)
        {
            return new ParsedAllPrintingsSet
            {
                BaseSetSize = deserializedSet.BaseSetSize,
                Block = deserializedSet.Block,
                Cards = deserializedSet.Cards?.Select(deserializedSetCard => new ParsedAllPrintingsSetCard
                {
                    Artist = deserializedSetCard.Artist,
                    AsciiName = deserializedSetCard.AsciiName,
                    Availability = deserializedSetCard.Availability,
                    BoosterTypes = deserializedSetCard.BoosterTypes,
                    BorderColor = deserializedSetCard.BorderColor,
                    CardParts = deserializedSetCard.CardParts,
                    ColorIdentity = deserializedSetCard.ColorIdentity,
                    ColorIndicator = deserializedSetCard.ColorIndicator,
                    Colors = deserializedSetCard.Colors,
                    ConvertedManaCost = deserializedSetCard.ConvertedManaCost,
                    EdhrecRank = deserializedSetCard.EdhrecRank,
                    FaceConvertedManaCost = deserializedSetCard.FaceConvertedManaCost,
                    FaceFlavorName = deserializedSetCard.FaceFlavorName,
                    FaceManaValue = deserializedSetCard.FaceManaValue,
                    FaceName = deserializedSetCard.FaceName,
                    Finishes = deserializedSetCard.Finishes,
                    FlavorName = deserializedSetCard.FlavorName,
                    FlavorText = deserializedSetCard.FlavorText,
                    ForeignData = deserializedSetCard.ForeignData?.Select(deserializedSetCardForeignDatum => new ParsedAllPrintingsForeignData
                    {
                        Language = deserializedSetCardForeignDatum.Language,
                        Name = deserializedSetCardForeignDatum.Name,
                        Type = deserializedSetCardForeignDatum.Type,
                        MultiverseID = deserializedSetCardForeignDatum.MultiverseId,
                        Text = deserializedSetCardForeignDatum.Text
                    }).ToArray(),
                    FrameEffects = deserializedSetCard.FrameEffects,
                    FrameVersion = deserializedSetCard.FrameVersion,
                    HandSizeModifier = deserializedSetCard.HandSizeModifier,
                    HasAlternativeDeckLimit = deserializedSetCard.HasAlternativeDeckLimit,
                    HasContentWarning = deserializedSetCard.HasContentWarning,
                    HasFoil = deserializedSetCard.HasFoil,
                    HasNonFoil = deserializedSetCard.HasNonFoil,
                    Identifiers = deserializedSetCard.Identifiers != null ? new ParsedAllPrintingsIdentifiers
                    {
                        CardKingdomEtchedId = deserializedSetCard.Identifiers.CardKingdomEtchedId,
                        CardKingdomFoilId = deserializedSetCard.Identifiers.CardKingdomFoilId,
                        CardKingdomId = deserializedSetCard.Identifiers.CardKingdomId,
                        CardsphereId = deserializedSetCard.Identifiers.CardsphereId,
                        McmId = deserializedSetCard.Identifiers.McmId,
                        McmMetaId = deserializedSetCard.Identifiers.McmMetaId,
                        MtgArenaId = deserializedSetCard.Identifiers.MtgArenaId,
                        MtgoFoilId = deserializedSetCard.Identifiers.MtgoFoilId,
                        MtgoId = deserializedSetCard.Identifiers.MtgoId,
                        MtgjsonV4Id = deserializedSetCard.Identifiers.MtgjsonV4Id,
                        MultiverseId = deserializedSetCard.Identifiers.MultiverseId,
                        ScryfallId = deserializedSetCard.Identifiers.ScryfallId,
                        ScryfallOracleId = deserializedSetCard.Identifiers.ScryfallOracleId,
                        ScryfallIllustrationId = deserializedSetCard.Identifiers.ScryfallIllustrationId,
                        TcgplayerProductId = deserializedSetCard.Identifiers.TcgplayerProductId,
                        TcgPlayerEtchedProductId = deserializedSetCard.Identifiers.TcgplayerEtchedProductId
                    } : null,
                    IsAlternativePrinting = deserializedSetCard.IsAlternativePrinting,
                    IsFullArt = deserializedSetCard.IsFullArt,
                    IsFunny = deserializedSetCard.IsFunny,
                    IsOnlineOnly = deserializedSetCard.IsOnlineOnly,
                    IsOversized = deserializedSetCard.IsOversized,
                    IsPromotionalPrinting = deserializedSetCard.IsPromotionalPrinting,
                    IsRebalancedForAlchemy = deserializedSetCard.IsRebalancedForAlchemy,
                    IsReprint = deserializedSetCard.IsReprint,
                    IsReserved = deserializedSetCard.IsReserved,
                    IsInStarterDeck = deserializedSetCard.IsInStarterDeck,
                    IsStorySpotlight = deserializedSetCard.IsStorySpotlight,
                    IsTextless = deserializedSetCard.IsTextless,
                    IsTimeshifted = deserializedSetCard.IsTimeshifted,
                    Keywords = deserializedSetCard.Keywords,
                    Language = deserializedSetCard.Language,
                    Layout = deserializedSetCard.Layout,
                    LeadershipSkills = deserializedSetCard.LeadershipSkills != null ? new ParsedAllPrintingsSetCardLeadershipSkills
                    {
                        IsBrawlLegal = deserializedSetCard.LeadershipSkills.IsBrawlLegal,
                        IsCommanderLegal = deserializedSetCard.LeadershipSkills.IsCommanderLegal,
                        IsOathbreakerLegal = deserializedSetCard.LeadershipSkills.IsOathbreakerLegal
                    } : null,
                    Legalities = deserializedSetCard.Legalities != null ? new ParsedAllPrintingsLegalities
                    {
                        Commander = deserializedSetCard.Legalities.Commander,
                        Duel = deserializedSetCard.Legalities.Duel,
                        Legacy = deserializedSetCard.Legalities.Legacy,
                        Oldschool = deserializedSetCard.Legalities.Oldschool,
                        Penny = deserializedSetCard.Legalities.Penny,
                        Premodern = deserializedSetCard.Legalities.Premodern,
                        Vintage = deserializedSetCard.Legalities.Vintage,
                        Pauper = deserializedSetCard.Legalities.Pauper,
                        Paupercommander = deserializedSetCard.Legalities.Paupercommander,
                        Modern = deserializedSetCard.Legalities.Modern,
                        Pioneer = deserializedSetCard.Legalities.Pioneer,
                        Alchemy = deserializedSetCard.Legalities.Alchemy,
                        Brawl = deserializedSetCard.Legalities.Brawl,
                        Explorer = deserializedSetCard.Legalities.Explorer,
                        Future = deserializedSetCard.Legalities.Future,
                        Gladiator = deserializedSetCard.Legalities.Gladiator,
                        Historic = deserializedSetCard.Legalities.Historic,
                        Historicbrawl = deserializedSetCard.Legalities.Historicbrawl,
                        Standard = deserializedSetCard.Legalities.Standard
                    } : null,
                    LifeTotalModifier = deserializedSetCard.LifeTotalModifier,
                    Loyalty = deserializedSetCard.Loyalty,
                    ManaCost = deserializedSetCard.ManaCost,
                    ManaValue = deserializedSetCard.ManaValue,
                    Name = deserializedSetCard.Name,
                    Number = deserializedSetCard.Number,
                    OriginalPrintingUUIDs = deserializedSetCard.OriginalPrintingUUIDs,
                    OriginalReleaseDate = deserializedSetCard.OriginalReleaseDate,
                    OriginalText = deserializedSetCard.OriginalText,
                    OriginalType = deserializedSetCard.OriginalType,
                    OtherFaceUUIDs = deserializedSetCard.OtherFaceUUIDs,
                    Power = deserializedSetCard.Power,
                    Printings = deserializedSetCard.Printings,
                    PromoTypes = deserializedSetCard.PromoTypes,
                    PurchaseUrls = deserializedSetCard.PurchaseUrls != null ? new ParsedAllPrintingsPurchaseUrls
                    {
                        CardKingdom = deserializedSetCard.PurchaseUrls.CardKingdom,
                        CardKingdomEtched = deserializedSetCard.PurchaseUrls.CardKingdomEtched,
                        CardKingdomFoil = deserializedSetCard.PurchaseUrls.CardKingdomFoil,
                        CardMarket = deserializedSetCard.PurchaseUrls.CardMarket,
                        Tcgplayer = deserializedSetCard.PurchaseUrls.Tcgplayer,
                        TcgplayerEtched = deserializedSetCard.PurchaseUrls.TcgplayerEtched
                    } : null,
                    Rarity = deserializedSetCard.Rarity,
                    RebalancedPrintingUUIDs = deserializedSetCard.RebalancedPrintingUUIDs,
                    Rulings = deserializedSetCard.Rulings?.Select(deserializedSetCardRuling => new ParsedAllPrintingsRuling
                    {
                        Date = deserializedSetCardRuling.Date,
                        Text = deserializedSetCardRuling.Text
                    }).ToArray(),
                    SecurityStamp = deserializedSetCard.SecurityStamp,
                    SetCode = deserializedSetCard.SetCode,
                    Side = deserializedSetCard.Side,
                    Signature = deserializedSetCard.Signature,
                    Subtypes = deserializedSetCard.Subtypes,
                    Supertypes = deserializedSetCard.Supertypes,
                    Text = deserializedSetCard.Text,
                    Toughness = deserializedSetCard.Toughness,
                    Type = deserializedSetCard.Type,
                    Types = deserializedSetCard.Types,
                    UUID = deserializedSetCard.UUID,
                    Variations = deserializedSetCard.Variations,
                    Watermark = deserializedSetCard.Watermark
                }).ToArray(),
                CardsphereSetId = deserializedSet.CardsphereSetId,
                Code = deserializedSet.Code,
                CodeV3 = deserializedSet.CodeV3,
                IsForeignOnly = deserializedSet.IsForeignOnly,
                IsFoilOnly = deserializedSet.IsFoilOnly,
                IsNonFoilOnly = deserializedSet.IsNonFoilOnly,
                IsOnlineOnly = deserializedSet.IsOnlineOnly,
                IsPaperOnly = deserializedSet.IsPaperOnly,
                IsPartialPreview = deserializedSet.IsPartialPreview,
                KeyruneCode = deserializedSet.KeyruneCode,
                McmId = deserializedSet.McmId,
                McmIdExtras = deserializedSet.McmIdExtras,
                McmName = deserializedSet.McmName,
                MtgoCode = deserializedSet.MtgoCode,
                Languages = deserializedSet.Languages,
                Name = deserializedSet.Name,
                ParentCode = deserializedSet.ParentCode,
                ReleaseDate = deserializedSet.ReleaseDate,
                TcgplayerGroupId = deserializedSet.TcgplayerGroupId,
                Tokens = deserializedSet.Tokens?.Select(deserializedSetToken => new ParsedAllPrintingsSetToken
                {
                    Artist = deserializedSetToken.Artist,
                    AsciiName = deserializedSetToken.AsciiName,
                    Availability = deserializedSetToken.Availability,
                    BoosterTypes = deserializedSetToken.BoosterTypes,
                    BorderColor = deserializedSetToken.BorderColor,
                    CardParts = deserializedSetToken.CardParts,
                    ColorIdentity = deserializedSetToken.ColorIdentity,
                    ColorIndicator = deserializedSetToken.ColorIndicator,
                    Colors = deserializedSetToken.Colors,
                    FaceName = deserializedSetToken.FaceName,
                    FaceFlavorName = deserializedSetToken.FaceFlavorName,
                    Finishes = deserializedSetToken.Finishes,
                    FlavorText = deserializedSetToken.FlavorText,
                    FrameEffects = deserializedSetToken.FrameEffects,
                    FrameVersion = deserializedSetToken.FrameVersion,
                    HasFoil = deserializedSetToken.HasFoil,
                    HasNonFoil = deserializedSetToken.HasNonFoil,
                    Identifiers = deserializedSetToken.Identifiers,
                    IsFullArt = deserializedSetToken.IsFullArt,
                    IsFunny = deserializedSetToken.IsFunny,
                    IsOnlineOnly = deserializedSetToken.IsOnlineOnly,
                    IsPromotionalPrinting = deserializedSetToken.IsPromotionalPrinting,
                    IsReprint = deserializedSetToken.IsReprint,
                    Keywords = deserializedSetToken.Keywords,
                    Language = deserializedSetToken.Language,
                    Layout = deserializedSetToken.Layout,
                    Loyalty = deserializedSetToken.Loyalty,
                    Name = deserializedSetToken.Name,
                    Number = deserializedSetToken.Number,
                    OtherFaceUUIDs = deserializedSetToken.OtherFaceUUIDs,
                    Power = deserializedSetToken.Power,
                    PromoTypes = deserializedSetToken.PromoTypes,
                    ReverseRelatedUUIDs = deserializedSetToken.ReverseRelatedUUIDs,
                    SecurityStamp = deserializedSetToken.SecurityStamp,
                    SetCode = deserializedSetToken.SetCode,
                    Side = deserializedSetToken.Side,
                    Signature = deserializedSetToken.Signature,
                    Subtypes = deserializedSetToken.Subtypes,
                    Supertypes = deserializedSetToken.Supertypes,
                    Text = deserializedSetToken.Text,
                    Toughness = deserializedSetToken.Toughness,
                    Type = deserializedSetToken.Type,
                    Types = deserializedSetToken.Types,
                    UUID = deserializedSetToken.UUID,
                    Watermark = deserializedSetToken.Watermark
                }).ToArray(),
                SealedProduct = deserializedSet.SealedProduct != null ? new ParsedAllPrintingsSetSealedProduct() : null,
                TotalSetSize = deserializedSet.TotalSetSize,
                Translations = deserializedSet.Translations != null ? new ParsedAllPrintingsSetTranslations
                {
                    ChineseSimplified = deserializedSet.Translations.ChineseSimplified,
                    ChineseTraditional = deserializedSet.Translations.ChineseTraditional,
                    French = deserializedSet.Translations.French,
                    German = deserializedSet.Translations.German,
                    Italian = deserializedSet.Translations.Italian,
                    Japanese = deserializedSet.Translations.Japanese,
                    Korean = deserializedSet.Translations.Korean,
                    PortugueseBrazil = deserializedSet.Translations.PortugueseBrazil,
                    Russian = deserializedSet.Translations.Russian,
                    Spanish = deserializedSet.Translations.Spanish
                } : null,
                Type = deserializedSet.Type
            };
        }
    }
}
