// <auto-generated />
using System;
using MTGDeckBuilder.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTGDeckBuilder.EF.Migrations
{
    [DbContext(typeof(MTGDeckBuilderContext))]
    partial class MTGDeckBuilderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardColorData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkColor");

                    b.HasIndex("fkColor");

                    b.ToTable("tblCardColor", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardColorIdentityData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkColorIdentity")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkColorIdentity");

                    b.HasIndex("fkColorIdentity");

                    b.ToTable("tblCardColorIdentity", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardData", b =>
                {
                    b.Property<int>("pkCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AsciiName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HandModifier")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasAlternateDeckLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsFunny")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LifeModifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Loyalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManaValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberInSet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Power")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Toughness")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("fkSet")
                        .HasColumnType("INTEGER");

                    b.HasKey("pkCard");

                    b.HasIndex("ManaValue");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("fkSet");

                    b.ToTable("tblCard", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardFormatData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkFormat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegal")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkFormat");

                    b.HasIndex("fkFormat");

                    b.ToTable("tblCardFormat", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardKeywordData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkKeyword")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkKeyword");

                    b.HasIndex("fkKeyword");

                    b.ToTable("tblCardKeywordData", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardSubTypeData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkSubType")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkSubType");

                    b.HasIndex("fkSubType");

                    b.ToTable("tblCardSubType", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardSuperTypeData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkSuperType")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkSuperType");

                    b.HasIndex("fkSuperType");

                    b.ToTable("tblCardSuperType", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardTypeData", b =>
                {
                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fkType")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkCard", "fkType");

                    b.HasIndex("fkType");

                    b.ToTable("tblCardType", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.ColorData", b =>
                {
                    b.Property<int>("pkColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkColor");

                    b.HasIndex("Color")
                        .IsUnique();

                    b.ToTable("tblColor", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.ColorIdentityData", b =>
                {
                    b.Property<int>("pkColorIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkColorIdentity");

                    b.HasIndex("ColorIdentity")
                        .IsUnique();

                    b.ToTable("tblColorIdentity", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.FileVersionData", b =>
                {
                    b.Property<int>("pkVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VersionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("pkVersion");

                    b.ToTable("tblFileVersion", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.FormatData", b =>
                {
                    b.Property<int>("pkFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkFormat");

                    b.HasIndex("Format")
                        .IsUnique();

                    b.ToTable("tblFormat", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.KeywordData", b =>
                {
                    b.Property<int>("pkKeyword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkKeyword");

                    b.HasIndex("Keyword")
                        .IsUnique();

                    b.ToTable("tblKeyword", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.PurchaseInformationData", b =>
                {
                    b.Property<int>("pkPurchaseInformation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardURI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorefrontName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("fkCard")
                        .HasColumnType("INTEGER");

                    b.HasKey("pkPurchaseInformation");

                    b.HasIndex("fkCard");

                    b.ToTable("tblPurchaseInformation", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.SetData", b =>
                {
                    b.Property<int>("pkSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSetSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSetSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("pkSet");

                    b.HasIndex("SetCode")
                        .IsUnique();

                    b.HasIndex("SetName")
                        .IsUnique();

                    b.ToTable("tblSet", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.SubTypeData", b =>
                {
                    b.Property<int>("pkSubType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkSubType");

                    b.HasIndex("SubType")
                        .IsUnique();

                    b.ToTable("tblSubType", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.SuperTypeData", b =>
                {
                    b.Property<int>("pkSuperType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuperType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkSuperType");

                    b.HasIndex("SuperType")
                        .IsUnique();

                    b.ToTable("tblSuperType", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.TypeData", b =>
                {
                    b.Property<int>("pkType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkType");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("tblType", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckCardData", b =>
                {
                    b.Property<int>("fkUserDeck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardUUID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CardDatapkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumCopies")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkUserDeck", "CardUUID");

                    b.HasIndex("CardDatapkCard");

                    b.ToTable("tblUserDeckCard", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckData", b =>
                {
                    b.Property<int>("pkUserDeck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardDatapkCard")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormatDatapkFormat")
                        .HasColumnType("INTEGER");

                    b.HasKey("pkUserDeck");

                    b.HasIndex("CardDatapkCard");

                    b.HasIndex("DateCreated");

                    b.HasIndex("DeckName");

                    b.HasIndex("FormatDatapkFormat");

                    b.ToTable("tblUserDeck", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckFormatData", b =>
                {
                    b.Property<int>("fkUserDeck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.HasKey("fkUserDeck", "Format");

                    b.ToTable("tblUserDeckFormat", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckSideboardCardData", b =>
                {
                    b.Property<int>("fkUserDeckSideboard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardUUID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CardDatapkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumCopies")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkUserDeckSideboard", "CardUUID");

                    b.HasIndex("CardDatapkCard");

                    b.ToTable("tblUserDeckSideboardCard", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckSideboardData", b =>
                {
                    b.Property<int>("fkUserDeck")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardDatapkCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pkSideBoardData")
                        .HasColumnType("INTEGER");

                    b.HasKey("fkUserDeck");

                    b.HasIndex("CardDatapkCard");

                    b.ToTable("tblUserDeckSideboard", (string)null);
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardColorData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardColors")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.ColorData", "Color")
                        .WithMany()
                        .HasForeignKey("fkColor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardColorIdentityData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardColorIdentities")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.ColorIdentityData", "ColorIdentity")
                        .WithMany("CardColorIdentities")
                        .HasForeignKey("fkColorIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("ColorIdentity");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.SetData", "Set")
                        .WithMany("SetCards")
                        .HasForeignKey("fkSet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardFormatData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardFormats")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.FormatData", "Format")
                        .WithMany("CardFormats")
                        .HasForeignKey("fkFormat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardKeywordData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardKeywords")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.KeywordData", "Keyword")
                        .WithMany("CardKeywords")
                        .HasForeignKey("fkKeyword")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardSubTypeData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardSubTypes")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.SubTypeData", "SubType")
                        .WithMany("CardSubTypes")
                        .HasForeignKey("fkSubType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("SubType");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardSuperTypeData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardSuperTypes")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.SuperTypeData", "SuperType")
                        .WithMany("CardSuperTypes")
                        .HasForeignKey("fkSuperType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("SuperType");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardTypeData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("CardTypes")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGDeckBuilder.EF.Entities.TypeData", "Type")
                        .WithMany("CardTypes")
                        .HasForeignKey("fkType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.PurchaseInformationData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", "Card")
                        .WithMany("PurchaseInformation")
                        .HasForeignKey("fkCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckCardData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", null)
                        .WithMany("UserDeckCardData")
                        .HasForeignKey("CardDatapkCard");

                    b.HasOne("MTGDeckBuilder.EF.Entities.UserDeckData", "UserDeck")
                        .WithMany("Cards")
                        .HasForeignKey("fkUserDeck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDeck");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", null)
                        .WithMany("UserDecks")
                        .HasForeignKey("CardDatapkCard");

                    b.HasOne("MTGDeckBuilder.EF.Entities.FormatData", null)
                        .WithMany("UserDecks")
                        .HasForeignKey("FormatDatapkFormat");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckFormatData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.UserDeckData", "Deck")
                        .WithMany("Formats")
                        .HasForeignKey("fkUserDeck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckSideboardCardData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", null)
                        .WithMany("UserDeckSideboardCards")
                        .HasForeignKey("CardDatapkCard");

                    b.HasOne("MTGDeckBuilder.EF.Entities.UserDeckSideboardData", "UserDeckSideboard")
                        .WithMany("Cards")
                        .HasForeignKey("fkUserDeckSideboard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDeckSideboard");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckSideboardData", b =>
                {
                    b.HasOne("MTGDeckBuilder.EF.Entities.CardData", null)
                        .WithMany("UserDeckSideboards")
                        .HasForeignKey("CardDatapkCard");

                    b.HasOne("MTGDeckBuilder.EF.Entities.UserDeckData", "UserDeck")
                        .WithOne("SideBoard")
                        .HasForeignKey("MTGDeckBuilder.EF.Entities.UserDeckSideboardData", "fkUserDeck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDeck");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.CardData", b =>
                {
                    b.Navigation("CardColorIdentities");

                    b.Navigation("CardColors");

                    b.Navigation("CardFormats");

                    b.Navigation("CardKeywords");

                    b.Navigation("CardSubTypes");

                    b.Navigation("CardSuperTypes");

                    b.Navigation("CardTypes");

                    b.Navigation("PurchaseInformation");

                    b.Navigation("UserDeckCardData");

                    b.Navigation("UserDeckSideboardCards");

                    b.Navigation("UserDeckSideboards");

                    b.Navigation("UserDecks");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.ColorIdentityData", b =>
                {
                    b.Navigation("CardColorIdentities");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.FormatData", b =>
                {
                    b.Navigation("CardFormats");

                    b.Navigation("UserDecks");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.KeywordData", b =>
                {
                    b.Navigation("CardKeywords");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.SetData", b =>
                {
                    b.Navigation("SetCards");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.SubTypeData", b =>
                {
                    b.Navigation("CardSubTypes");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.SuperTypeData", b =>
                {
                    b.Navigation("CardSuperTypes");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.TypeData", b =>
                {
                    b.Navigation("CardTypes");
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckData", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Formats");

                    b.Navigation("SideBoard")
                        .IsRequired();
                });

            modelBuilder.Entity("MTGDeckBuilder.EF.Entities.UserDeckSideboardData", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
